defaults:
  actions:
    comment:
      bot_account: hugbunt3r1
queue_rules:
  - name: default
    merge_conditions:
      - -conflict
    merge_method: squash
pull_request_rules:
  - name: queue-entry-gate
    conditions:
      - label = ready-to-merge
    actions:
      queue:
        name: default
  - name: echo-title
    conditions:
      - -closed
      - -head~=^mergify/
    actions:
      comment:
        message: "{{ title }}"
