queue_rules:
  - name: default
    merge_conditions: []
    merge_method: squash
pull_request_rules:
  - name: auto-queue
    conditions:
      - label = queue-me
    actions:
      queue:
        name: default